ABPindo/indonesianadblockrules

abpindo_computer_prank.txt
Liveleak is a popular video sharing website.
=> Allow liveleak.com

abpindo_specific_block.txt, abpindo_specific_hide.txt
Sembunyikan artikel panjang yang tidak jelas di website referral dari Samehadaku.
Di Tribunnews ada iklan di sidebar kiri dan di header:
[Gambar 1](https://user-images.githubusercontent.com/8542502/43215745-3980e5b0-9067-11e8-85da-1211586b17f2.png)
Jika iklan di header diblok, navigasi halaman utamanya tersembunyi. Kalau yang ini bagaimana ya?
[Gambar 2](https://user-images.githubusercontent.com/8542502/43215812-65256326-9067-11e8-84d7-67fdb529ce19.png)
[Gambar 1](https://user-images.githubusercontent.com/8542502/43217421-c9eac220-906b-11e8-932b-d30b8d0aed52.png)
Iklan FJB kaskus di sidebar kanan [thread](https://www.kaskus.co.id/thread/5b54076f1a9975c87e8b4574/mengintip-persiapan-qatar-sang-tuan-rumah-piala-dunia-2022/):
[Gambar …
=> A:tetew.info,greget.space and others

README.md, abpindo_annoyance.txt, abpindo_annoyance_elemhide.txt, abpindo_specific_block.txt, abpindo_specific_hide.txt, subscriptions/abpindo.txt, subscriptions/abpindo_noelemhide.txt, subscriptions/abpindo_tanpanawala.txt
Update `wp-content/uploads/*/*/*.gif` ke `wp-content/uploads/*.gif$image`
=> Fix styling

abpindo_specific_block.txt, abpindo_specific_hide.txt
Block css iklan dan script js dari Google Analytics dan Eyeota di Detik.
[Gambar 1](https://user-images.githubusercontent.com/8542502/43354956-65e3ae58-927e-11e8-925f-a9579768c06b.png)
[Gambar 2](https://user-images.githubusercontent.com/8542502/43354957-664a01d0-927e-11e8-8eff-5024eebfe7b0.png)
[Gambar 1](https://user-images.githubusercontent.com/8542502/43355228-26ec83f0-9283-11e8-8da7-450fa59e40cd.png)
[Gambar 1](https://user-images.githubusercontent.com/8542502/43355260-bb5e4fc8-9283-11e8-83b8-d4433cc2b7d1.png)
[Gambar 1](https://user-images.githubusercontent.com/8542502/43355368-1c1f926c-9285-11e8-8d05-0efb13316a68.png)
=> A:detik.com & lainnya

abpindo_specific_hide.txt, subscriptions/abpindo.txt, subscriptions/abpindo_noannoyance.txt, subscriptions/abpindo_noelemhide.txt
Artikel iklan shortlink website seperti di greget.space dan tetew.info dari Samehadaku.
Link: https://www.siherp.com/VSrID
=> A: siherp.com

abpindo_specific_hide.txt
=> banner bawah

abpindo_specific_hide.txt
menghilangkan iklan banner
dari web indoxx1.art
=> indoxx1.art

src/elementhide/specific_hide.txt
=> A: budiarto.id/bausastra

src/advert/specific_block.txt
Block redirect popup at https://komikindo.id/
To reproduce: Test as mobile
=> A: https://komikindo.id/

src/advert/adservers.txt
Block adserver related to redirects
Screenshot:
=> A: https://komikcast.com/

src/advert/adservers.txt
Block adserver responsible for popup ads
Screenshots:
=> A: [NSFW] https://mangasusu.co.in/

src/advert/adservers.txt
Block adserver at https://komiktap.in/
Screenshot:
=> A: https://komiktap.in/

src/advert/adservers.txt
Block adserver responsible for popup messages
Screenshots:
=> A:  https://anoboy.online/

src/advert/adservers.txt
Block adserver at https://mangakita.net/
Screenshot:
=> A: https://mangakita.net/

src/advert/specific_hide.txt
Hide top banners at https://kazefuri.net/
Screenshot:
=> A: https://kazefuri.net/

src/advert/specific_hide.txt
Hide bottom banner at https://www.semprot.com/
Scrrenshots:
=> A: https://www.semprot.com/

src/advert/adservers.txt
Block adserver related to popup messages at https://dramaindo.xyz/
Screenshots:
=> A: https://dramaindo.xyz/

src/advert/adservers.txt
Block adserver responsible for redirect popups at https://anichin.my.id/
Screenshot:
=> A: https://anichin.my.id/

src/advert/adservers.txt
Block adserver related to redirects at https://sektekomik.com/
Screenshots:
=> A: https://sektekomik.com/

README.md
Referensi:
- https://kbbi.kemdikbud.go.id/entri/baru%20(1)
- https://kbbi.kemdikbud.go.id/entri/baharu
- https://twitter.com/ivanlanin/status/963816366431072256
- https://www.katabaku.com/2015/12/memperbarui-memperbaharui-membarui.html
- https://www.katabaku.com/2015/12/diperbarui-atau-diperbaharui-yang-benar.html
- Google secara resmi dalam salah satu halamannya memakai kata "pembaruan", https://policies.google.com/privacy/archive?hl=id
=> docs: "baharu" to "baru"

src/advert/adservers.txt, src/advert/specific_hide.txt
Block adserver and banner at https://kiryuu.id/
Screenshots:
=> A: https://kiryuu.id/

src/advert/specific_block.txt, src/advert/specific_hide.txt
Hide banners all over the pages at https://80.209.252.146/
Screenshots:
=> A: https://80.209.252.146/

src/advert/adservers.txt
Block adserver related to popup messages at https://anoboy.watch/
Screenshot:
=> A: https://anoboy.watch/

src/advert/adservers.txt
Block adserver related to banners at https://anoboy.online/
<details>
<summary>Screenshot [NSFW]</summary>
</details>
=> A: https://anoboy.online/

src/advert/adservers.txt
Block adserver related to redirects at https://nontonanimeid.one/
Screenshot:
=> A: https://nontonanimeid.one/

src/advert/adservers.txt
Block adserver at https://mangaceng.com/
Screenshot:
=> A: https://mangaceng.com/

src/advert/adservers.txt, src/advert/specific_hide.txt
Block adserver + banners at https://drakorindo.best/
Screenshot:
=> A: https://drakorindo.best/

src/advert/adservers.txt
Block adserver at https://ganooll.xyz/
Screenshot:
=> A: https://ganooll.xyz/

src/advert/specific_hide.txt
Hide placeholder at https://news.detik.com/
Screenshot:
=> A: https://news.detik.com/

src/advert/specific_hide.txt
Hide banners at https://otakudesu.pro/
Screenshots:
=> A: https://otakudesu.pro/

src/advert/specific_block.txt
Block image popups at https://bacakomik.co/
Screenshots:
=> A: https://bacakomik.co/

src/advert/specific_hide.txt
Hide placeholders at https://www.kompas.com/
**Tested as mobile** 
Screenshots:
=> A: https://www.kompas.com/

src/advert/specific_hide.txt
Hide ads at https://oploverz.fan/
**Mobile**
Screenshot:
=> A: https://oploverz.fan/

src/advert/specific_hide.txt
Block adserver at https://149.56.24.226/
Screenshot:
=> A: https://149.56.24.226/

src/advert/specific_hide.txt
Hide banners and hide promo overlay at https://185.231.223.76/
Screenshot:
=> A: https://185.231.223.76/

src/advert/specific_hide.txt
Hide popups at https://komikstation.co/
Screenshot:
=> A: https://komikstation.co/

src/advert/adservers.txt
Block adservers at http://manhwalands.xyz/
Screenshots:
=> A: http://manhwalands.xyz/

src/advert/adservers.txt
Block adserver at https://193.178.172.113/
Screenshot:
=> A: https://193.178.172.113/

src/advert/specific_hide.txt
=> A: https://m.bisnis.com/

README.md
Menambahlan tanda titik di akhir kalimat yang ada di list agar terlihat konsisten dengan kalimat-kalimat yang sudah ada.
=> docs: Tambahkan tanda titik di akhir kalimat

src/advert/specific_hide.txt
Hide banner at https://nanimex.org/
Screenshot:
=> A: https://nanimex.org/

src/advert/specific_hide.txt
Hide banners at https://komikindo.me/
Screenshots:
=> A: https://komikindo.me/

src/advert/specific_hide.txt
Hide banners at https://mareceh.com/
Screenshots:
=> A: [NSFW] https://mareceh.com/

src/advert/specific_block.txt, src/advert/specific_hide.txt
Popups/banners at https://manhwaindo.id/
=> A: https://manhwaindo.id/

src/advert/specific_hide.txt
Hide popup messages at https://bacamanga.id/
Screenshot:
=> A: https://bacamanga.id/

src/advert/adservers.txt
=> add offdeck.telkomsel.com

src/advert/specific_hide.txt
Hide banners at https://mangaku.vip/
and https://manganime.in/
=> A: https://mangaku.vip/

src/advert/specific_hide.txt
Banners at https://www.rasa.my/
=> A: https://www.rasa.my/

src/advert/specific_hide.txt
Overlay at https://212.32.226.234/
=> A: https://212.32.226.234/

src/advert/specific_hide.txt
Hide banners + backdrop at https://nanimex.in/
=> A: https://nanimex.in/

src/advert/adservers.txt, src/advert/general_block.txt
Hi, could you please review this adservers found on this page. 
Kind regards.
=> A: https://oploverz.co.in/

src/advert/specific_hide.txt
Hello, please add this domain to the existing filter on the list to hide this banner ads: 
Thank you
=> A: `https://anichin.vip/`

src/advert/specific_hide.txt
Hi, please add this filter to eliminate the top banner ads
Thank you in advance
=> A: `https://bioskopkeren.beauty/`

src/advert/specific_hide.txt
Hi, Please add this filter to hide the top banner ads on this domain
Thank you
=> A: `komikindo.id`

src/advert/specific_hide.txt
Hi, Please review and add this filter to hide ads found on this page:  
Thank you
=> A: `westmanga.info`

src/advert/specific_hide.txt
Hi please add these filters to hide this banner ads on the page:  
Thank you
=> A: `animasu.nl`

src/advert/specific_hide.txt
Hi please add this filter to hide this banner ads on the page:
Thanks
=> A: `komikindo.pro`

src/advert/specific_hide.txt
Hi please add this filters to hide this ads on the page:
Thank you
=> A:`samehadaku.run`

src/advert/specific_hide.txt
Hi please add this domain to the existing filter there are ad banners on top of the page  Thank you
=> A: `oploverz.info`

src/advert/specific_hide.txt
hi 🤗 please add this domain to the existing filters, lots of banners and ads embedded on page. Thank you
=> A: `oploverz.tv`

src/advert/specific_hide.txt
Hi please add these filters to hide the ads on page:
thank you
=> A: `komikindo.co`

src/advert/specific_hide.txt
New `oploverz` domain full with ads:
Thank you
=> A:`oploverz.top`

src/advert/specific_hide.txt
Ads in search on the domains
On the desktop `[tokopedia.com#?#div[data-testid=](http://tokopedia.com/#?#div[data-testid=)"divProductWrapper"]:-abp-has(span[data-testid="divSRPTopadsIcon"])` 
on mobile: `[tokopedia.com#?#div[data-testid=](http://tokopedia.com/#?#div[data-testid=)"master-product-card"]:-abp-has(span[data-testid="linkProductTopads"])`
Thank you
=> A: `tokopedia.com`

src/advert/specific_hide.txt
Promoted products on the desktop and mobile site.
<details>
<summary>Desktop:</summary>
</details>
<details>
<summary>Mobile:</summary>
</details>
=> A: `bukalapak.com`

src/advert/specific_hide.txt
Promoted products on the desktop and mobile site.
<details>
<summary>Desktop:</summary>
</details>
<details>
<summary>Mobile:</summary>
</details>
=> A: `blibli.com`

src/advert/specific_hide.txt
This commit includes:
- promoted store carousel in desktop and mobile,
<details>
<summary>Desktop:</summary>
</details>
<details>
<summary>Mobile:</summary>
</details>
- recommended products on the home page of desktop and mobile,
<details>
<summary>Desktop:</summary>
</details>
<details>
<summary>Mobile:</summary>
</details>
- promoted store card on mobile, and
<details>
<summary>Mobile:</summary>
</details>
- featured shop on mobile.
<details>
<summary>Mobile:</summary>
</details>
=> M: `tokopedia.com`

src/advert/specific_hide.txt
I accidentally use a procedural marker on a declarative filter in the previous pull request, which will affect performance. This commit will fix that.
=> M: Do not use procedural marker on declarative filters

src/advert/specific_hide.txt
Hides popup dialog.
This commit fixes https://github.com/ABPindo/indonesianadblockrules/issues/414.
=> A: `gudangmovies21.skin`

src/advert/scriptlet_ublock.txt
This pull request
- prevents the site from clearing console, and
- prevents anti-adblock.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1439.
=> A: `netq.me`

abpindo.template, abpindo_noadult.template, abpindo_noelemhide.template
Properly, this time.
Related discussion:
https://github.com/ABPindo/indonesianadblockrules/commit/56cc48b43bf443532b61d5fc2a012a90a8593537#commitcomment-122033649
=> M: Remove Adblock Plus' snippet filter file

src/advert/scriptlet_ublock.txt, src/advert/specific_hide.txt
This pull request:
- prevents anti-blocker,
- boosts timer, and
- hides fake download button.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1455.
=> A: `info.gambar.pro`

src/advert/specific_hide.txt
This pull request addresses https://github.com/realodix/AdBlockID/issues/1460.
=> A: `beritasatu.com`

src/advert/scriptlet_ublock.txt, src/advert/specific_hide.txt
This pull request:
- hides ad banner leftover and
- prevents anti-blocker (defence-in-depth).
This pull request addresses https://github.com/realodix/AdBlockID/issues/1459.
=> A: `thejakartapost.com`

src/adult/adult_specific_block.txt, src/advert/specific_hide.txt
Blocks gambling advertisement.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1463.
=> A: `samehadaku.skin`

src/advert/allowlist.txt, src/advert/scriptlet_ublock.txt, src/advert/specific_block.txt, src/advert/specific_hide.txt
Prevents anti-blocker.
This pull request fixes #427.
Related issue:
https://github.com/uBlockOrigin/uAssets/issues/18518
=> A: `doroni.me`

src/advert/specific_hide.txt
Hides popup banner.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1465.
=> A: `shinigami.id`

src/advert/specific_hide.txt
Hides ad banner and ad placeholders.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1466.
=> A: `tirto.id`

src/advert/specific_hide.txt
Hides ad placeholders.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1467.
=> A: `katadata.co.id`

src/adult/adult_specific_hide.txt, src/advert/adservers.txt, src/advert/allowlist.txt, src/advert/specific_hide.txt
Also label some sections for clarity.
=> M: Group entity filters

src/advert/specific_block.txt
Blocks ad banner.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1470.
=> A: `mangakyo.org`

src/advert/scriptlet_ublock.txt, src/advert/specific_hide.txt
This pull request
- prevents anti-blocker,
- boosts timer, and
- hides fake download button.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1477.
=> A: `jenismac.com`

src/advert/specific_hide.txt
Hides ad banners.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1478.
=> A: `animasu.cc`

src/advert/specific_hide.txt
This pull request addresses https://github.com/realodix/AdBlockID/issues/1488.
=> A: `merdeka.com`

src/advert/specific_hide.txt
This pull request addresses https://github.com/realodix/AdBlockID/issues/1494.
=> A: `mangaindo.me`

src/advert/specific_hide.txt
Hides ad banner leftover.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1495.
=> A: `mgkomik.com`

src/advert/specific_hide.txt
This pull request addresses https://github.com/realodix/AdBlockID/issues/1497.
=> A: `starringheavenlyrics.blogspot.com`

src/advert/allowlist.txt
This pull request removes obsolete exception filters.
=> M: Remove obsolete exception filters

src/advert/specific_hide.txt
Hides ad banner placeholders.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1518.
=> A: `jendelakaba.com`

src/advert/allowlist.txt
Unhides self-promotion banner.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1522.
=> P: `tokosatu.com`

src/advert/scriptlet_ublock.txt, src/advert/specific_block.txt
Prevents popup ad.
This pull request addresses https://github.com/uBlockOrigin/uAssets/issues/19477.
=> A: `anichin.top`

src/advert/specific_hide.txt
Hides ad banner leftover.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1526.
=> A: `warungkomik.com`

src/advert/specific_block.txt, src/advert/specific_hide.txt
Blocks ad banner and hides ad banner placeholder.
This pull request fixes https://github.com/ABPindo/indonesianadblockrules/issues/544.
=> A: `baladfilm.skin`

src/advert/specific_hide.txt
=> A: `pikiran-rakyat.com`

src/advert/specific_hide.txt
Hides desktop and mobile ad placeholders.
=> M: `kontan.co.id`

src/advert/specific_hide.txt
Hides ad banner placeholder.
An example link can be accessed via `https://m.bareksa.com/id/data/reksadana/daftar`.
=> A: `bareksa.com` (Mobile UA)

src/advert/specific_hide.txt
Hides desktop and mobile ad banner placeholders.
=> A: `marketeers.com`

src/advert/specific_hide.txt
=> A: `chordtela.com`

src/advert/specific_hide.txt
Hides desktop ad banner leftovers and placeholders.
=> A: `kontan.co.id`

src/advert/specific_hide.txt
Hides desktop and mobile ad banner placeholders.
=> M: `sonora.id`

src/advert/specific_hide.txt
Top banners at https://tv3.lk21official.mom/
=> A: lk21official.mom

src/advert/specific_block.txt
Several gif banners at https://kalashainternational.com/fancy-dance-2024/
=> A: kalashainternational.com

src/advert/specific_hide.txt
Hides ad banner placeholders and leftovers.
=> A: `dataindonesia.id`

src/advert/specific_hide.txt
Hides desktop and mobile ad banner placeholders.
=> A: `cnbcindonesia.com`

src/advert/specific_hide.txt
The leftovers can be found on the site's main page and lyric pages.
=> A: `kordindonesia.com` (mobile UA)

src/advert/specific_hide.txt
Hides promoted rooms on desktop and mobile.
=> A: `mamikos.com`

src/advert/specific_block.txt, src/advert/specific_hide.txt
Hides ad banners.
This pull request addresses https://github.com/uBlockOrigin/uAssets/issues/25011.
=> A: `shinigami03.com`

src/advert/specific_hide.txt
Hides ad banner placeholders.
This pull request addresses https://github.com/realodix/AdBlockID/issues/1827.
=> A: `cubmu.com`

src/advert/specific_block.txt, src/advert/specific_hide.txt
Blocks ad banners.
This pull request addresses https://github.com/uBlockOrigin/uAssets/issues/25146.
=> A: `nomat.top`

src/advert/specific_block.txt, src/advert/specific_hide.txt
=> A: `emitennews.com`

src/advert/specific_block.txt, src/advert/specific_hide.txt
=> A: `koran-jakarta.com`

src/advert/specific_block.txt
Blocks promoted products.
A test page can be accessed via `https://bukukord.com/chord/all-i-want-for-christmas-is-you-mariah-carey`.
=> A: `bukukord.com`

src/advert/specific_hide.txt
Hides desktop and mobile ad placeholders.
=> A: `ayobandung.com`

src/advert/specific_hide.txt
=> P: `tokopedia.com`

src/advert/specific_hide.txt
Hides desktop and mobile ad banner placeholders.
=> A: `idntimes.com`

src/advert/specific_hide.txt
=> A: `timesindonesia.co.id`

src/advert/specific_hide.txt
=> A: `trenasia.com`

src/advert/specific_hide.txt
Hides ad banners.
This pull request fixes https://github.com/ABPindo/indonesianadblockrules/issues/602.
=> A: `cosmic1.co`

src/advert/specific_hide.txt
=> A: `jakartaglobe.id`

src/advert/specific_hide.txt
Hides ad banners.
This pull request fixes https://github.com/ABPindo/indonesianadblockrules/issues/606.
=> A: `beritacyber.com`

src/advert/specific_block.txt, src/advert/specific_hide.txt
=> Added new shinigami domain and removed unused ones

src/advert/specific_hide.txt, subscriptions/abpindo.txt, subscriptions/abpindo_extended.txt, subscriptions/abpindo_hosts.txt, subscriptions/abpindo_hosts_adult.txt, subscriptions/abpindo_noadult.txt, subscriptions/abpindo_noelemhide.txt
```
detik.com##.float-vid__content
```
=> detik.com - recommended video pop-up

src/advert/specific_hide.txt
https://www.kompas.id/artikel/27-tahun-reformasi-kasus-pelanggaran-ham-berat-masih-menggantung (Premium)
=> kompas.id - empty ads placeholder

src/advert/specific_hide.txt, src/annoyances.txt
=> kompasiana.com

src/annoyances.txt
=> detik.com - news reload notification

src/annoyances.txt
=> haibunda.com - enable notification banner

src/advert/specific_hide.txt
posisi dan filter rule sama dengan #714, ditambah:
=> popbela.com - empty ads placeholder

src/advert/specific_hide.txt
=> popmama.com - empty ads placeholder

src/advert/specific_hide.txt, src/annoyances.txt
URLs:https://bobo.grid.id/read/084253181/cara-menghitung-volume-kerucut-dan-contoh-soal-materi-matematika?page=all
=> grid.id - hide ads

src/annoyances.txt
=> Reopen issues #699

src/annoyances.txt
popbela.com, popmama.com, cnnindonesia.com. Android app download banner
=> [annoyances] popbela.com popmama.com cnnindonesia.com

src/annoyances.txt
https://www.idntimes.com/news/indonesia/muhammad-ilman-nafian-2/satukan-visi-megawati-pdip-gelar-bimtek-anggota-dprd-se-kalimantan?page=all
=> idntimes.com - next article popup

src/advert/specific_hide.txt
https://www.hitekno.com/gadget/2022/11/29/140956/kisah-hp-nokia-jadul-pak-sby-yang-bikin-panas-hubungan-indonesia-dan-australia-bersejarah
Sama saya buat comment khusus untuk grid/idn
networks agar mudah di-update
=> hitekno.com - empty ads placeholder 

src/advert/specific_hide.txt
https://ww1.anoboy.app/2025/05/aru-majo-ga-shinu-made-episode-9/
=> A: .anoboy.app

src/advert/specific_hide.txt
https://nasional.kompas.com/read/2025/05/28/06245191/presiden-perancis-emmanuel-macron-temui-prabowo-di-istana-hari-ini?source=headline
=> Close ad button - kompas.com

src/annoyances.txt
=> insertlive.com - android app banner

src/advert/specific_hide.txt
=> idntimes.com - empty ads placeholder

src/advert/specific_block.txt, src/advert/specific_hide.txt
=> tempo.co - empty ads placeholder

src/advert/specific_hide.txt
https://narasi.tv/read/narasi-daily/prabowo-hadiri-ktt-ke-46-asean-di-kuala-lumpur-convention-centre-didampingi-beberapa-menteri-dari-kabinet-merah-putih
=> narasi.tv - close ads button

src/annoyances.txt
=> bolasport.com, bobo.grid.id - self promotion

src/advert/specific_hide.txt
https://www.herworld.co.id/article/2025/5/33025-Independen-Ini-5-Pilihan-Bisnis-yang-Cocok-untuk-Wanita
=> herworld.co.id - empty ads placeholder

src/advert/specific_hide.txt
=> A: kilat.com Issue #746

src/advert/specific_hide.txt
=> beritasatu.com - empty ads billboard

src/annoyances.txt
=> sasa.co.id - cookie consent

src/advert/specific_hide.txt
=> beritasatu.com - empty ads header

src/annoyances.txt
=> yummy.co.id - annoyances

src/annoyances.txt
=> ggwp.id,fortuneidn.com,duniaku.idntimes.com - apply rule from grid/idn networks (annoyance)

src/annoyances.txt
=> inilah.com - social widget

src/annoyances.txt
=> kumparan.com - social button

src/annoyances.txt
=> tribunnews.com - next article banner

src/advert/specific_hide.txt
=> grid/idn networks - issues #762

src/advert/specific_hide.txt
=> A: zonajakarta.com

src/annoyances.txt
=> theasianparent.com - app download banner

src/advert/specific_hide.txt
=> A: sonora.id

src/advert/specific_hide.txt
=> A: motorplus-online.com

src/annoyances.txt
=> motorplus-online.com - video

src/advert/specific_hide.txt
=> A: IDN Networks

src/advert/specific_block.txt, src/advert/specific_hide.txt
=> A: tempo.co

src/annoyances.txt
=> Annoyance: republika.co.id

abpindo_annoyances.template, abpindo_extended.template, abpindo_hosts_adult.template, abpindo_noadult.template, abpindo_noelemhide.template
Agar lebih rapi dan tidak confuse dengan annoyance dan adult
=> Update title pada subscriptions

src/annoyances.txt
=> Issue #805

src/annoyances.txt
=> jakartaglobe.id - login pop-up

src/advert/specific_hide.txt
=> A: beritasatu.com

src/annoyances.txt
=> Annoyance: bloombergtechnoz.com

src/advert/specific_hide.txt, src/annoyances.txt
=> Reopen #837

src/advert/specific_hide.txt
=> A: cnbcindonesia.com (mobile)

src/advert/specific_hide.txt
=> A: wolipop.detik.com

src/advert/specific_hide.txt
=> A: Okezone.com

src/advert/specific_hide.txt
=> A: industry.co.id

src/advert/specific_hide.txt
=> A: kompasiana.com

src/advert/specific_hide.txt
=> A: genpi.co

src/annoyances.txt
=> Annoyance: kompas.tv

src/annoyances.txt
=> Annoyance: brainacademy.id,english-academy.id,ruangguru.com

src/adult/adult_specific_hide.txt
=> A: https://minioppai.org

src/annoyances.txt
=> Annoyance: jpnn.com 

src/advert/specific_hide.txt
=> A: narasi.tv

src/advert/general_hide.txt, src/advert_extended.txt
namun, untuk div-gpt-ads tidak selalu berhasil, contohnya pada filter ini:
sindonews.com###me-div-gpt-ad-leaderboard
=> Proposed addition to general_hide

src/advert/specific_hide.txt
=> A: muslimterkini.id, hops.id, unews.id

src/advert/specific_hide.txt
Patches from: https://github.com/realodix/AdBlockID/commit/cce9dbfff32df28818f8d9f476ae7ccc6e0c4b4b
=> A: Republika.co.id

src/advert/specific_hide.txt
This hides the online gambling banner popup when entering the page
=> Kiryuu02.com

src/advert/specific_hide.txt
=> A: kapanlagi.com

src/advert/specific_hide.txt
=> A: KLY Youniverse

src/advert/specific_hide.txt
=> A: indonesiana.id

src/advert/specific_hide.txt, src/annoyances.txt
=> A: beritaharian.sg

src/adult/adult_specific_block.txt
Filter ini memblokir banner iklan, saya tempatkan disini karena ada konten dewasa didalam websitenya dan mengirit syntax fiter
=> Filter for ABPindo/indonesianadblockrules/issues/939

src/advert/specific_hide.txt
=> https://parcelsapp.com

src/advert/specific_hide.txt
Filter ini memblokir banner floating dan banner player di `anime.oploverz.ac` dan memblokir element yang menyebabkan iklan popup pada web `v1.samehadaku.how`
=> Banner ads blocking for Oploverz and Samehadaku

src/advert/specific_block.txt
XML request yang sebelumnya sudah terdaftar telah diubah oleh pemilik server, mungkin akan butuh filtering secara berkala
=> Iklan video animekompi
